Management Debt/Areas/Admin/Controllers/AdminHomeController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using Management_Debt.Models;

namespace Management_Debt.Areas.Admin.Controllers
{
	public class AdminHomeController : Controller
	{
		// GET: Admin/AdminHome
		public ActionResult Index(int? page, int? status, string find)
		{
			using (DBContext1 db = new DBContext1())
			{
				page = page ?? 1;
				status = status ?? 3;
				find = find ?? "";
				var link = (from l in db.Debtor where l.full_name.Contains(find) select l).OrderBy(l => l.did);

				if (status == 0)
				{
					link = (from l in db.Debtor where l.status == 0 && l.full_name.Contains(find) select l).OrderBy(l => l.did);
				}
				else if (status == 1)
				{
					link = (from l in db.Debtor where l.status == 1 && l.full_name.Contains(find) select l).OrderBy(l => l.did);
				}
				Session["status"] = status;
				//Response.Write("<script>alert('" + status + "')</script>");
				int pageSize = 11;
				int pageNumber = (page ?? 1);
				return View(link.ToPagedList(pageNumber, pageSize));
			}
		}

		[HttpGet]
		public ActionResult addDebtor()
		{
			return View();
		}

		[HttpPost]
		public ActionResult addDebtor(Debtor debtor)
		{
			using (DBContext1 db = new DBContext1())
			{
				var item = db.Debtor.FirstOrDefault(m => m.did == debtor.did || m.email == debtor.email);
				if (item == null)
				{
					// Add data to the particular table
					ViewBag.message = "Thêm thành công!";
					ViewBag.m = "succ";
					db.Debtor.Add(debtor);
					db.SaveChanges();
				}
				else
				{
					ViewBag.message = "Người nợ này đã tồn tại!";
					ViewBag.m = "error";
				}
			}
			return View("addDebtor");
		}

		[HttpGet]
		public ActionResult updateDebtor(string id)
		{
			using (DBContext1 db = new DBContext1())
			{
				var item = db.Debtor.FirstOrDefault(m => m.did == id);

				return View(item);

			}
		}

		[HttpPost]
		public ActionResult updateDebtor(string id, Debtor debtor)
		{
			using (DBContext1 db = new DBContext1())
			{
				var checkDuplicate = db.Debtor.FirstOrDefault(z => z.did != id && z.email == debtor.email);
				if (checkDuplicate == null)
				{
					var item = db.Debtor.FirstOrDefault(m => m.did == id);
					item.full_name = debtor.full_name;
					item.status = debtor.status;
					item.address = debtor.address;
					item.birthday = debtor.birthday;
					db.SaveChanges();
				}
				return RedirectToAction("Index");

			}

		}
		[HttpGet]
		public ActionResult removeDebtor(string id)
		{
			using (DBContext1 db = new DBContext1())
			{
				var item = db.Debtor.FirstOrDefault(m => m.did == id);
				if (item != null)
				{
					db.Debtor.Remove(item);
					db.SaveChanges();
				}
				return RedirectToAction("Index");
	
			}
		}

		[HttpPost]
		public ActionResult SearchByName(FormCollection collection)
		{
			string find = collection["search"].ToString();
			return RedirectToAction("Index", new {find});
		}
	}
}

Management Debt/Areas/Admin/Views/AdminHome/Index.cshtml
@using PagedList.Mvc;
@model  PagedList.PagedList<Management_Debt.Models.Debtor>
@{
    ViewBag.Title = "Index";
    var s = Session["status"];

    int status = (s == null) ? 3 : int.Parse(s.ToString());
}
@section css{
    <link rel="stylesheet" type="text/css" href="~/Areas/Admin/Content/css/home.admin.css" />
    <!-- Option 1: Include in HTML -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
    <link rel="stylesheet" href="~/Areas/Admin/Content/css/form.add.css" />
    <link rel="stylesheet" href="~/Areas/Admin/Content/css/pager.css" />
}


<div class="content">
    <a href="@Url.Action("addDebtor","AdminHome")" id="btnAdd1" style="margin-top: 30px;" class="btnAdd1">
        <i class="bi bi-plus-square"></i>
        Add
    </a>
    <div class="container">
        <div class="top">
            <div class="info-debtor">
                <h2>Thông tin người nợ</h2>
                <p>Tổng cộng: @Model.Count bản ghi</p>
            </div>
            <div class="filter">
                <label for="loc">Hiển thị theo:</label>
                <select name="loc" id="status" onchange="change(this);">
                    <option value="3">Tất cả</option>
                    <option value="0">Chưa trả hết nợ</option>
                    <option value="1">Đã trả hết nợ</option>
                </select>
            </div>
        </div>
        <hr />
        <table>
            <tr>
                <th>ID</th>
                <th>Full name</th>
                <th>Email</th>
                <th>Address</th>
                <th>Birthday</th>
                <th>Status</th>
                <th>Action</th>
            </tr>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.did</td>
                    <td>@item.full_name</td>
                    <td>@item.email</td>
                    <td>@item.address</td>
                    <td>@item.birthday</td>
                    @if (item.status == 1)
                    {
                        <td>
                            Đã trả hết nợ
                        </td>
                    }
                    else
                    {
                        <td>
                            Chưa trả hết nợ
                        </td>
                    }
                    <td>
                        <a href="@Url.Action("updateDebtor", "AdminHome", new {id=item.did})" class="btnEdit">
                            <i class="bi bi-pencil-square"></i>
                        </a>
                        <a href="@Url.Action("removeDebtor", "AdminHome", new {id=item.did})" class="btnDelete" onclick="return confirm(`Are you sure to want to delete this debtor?`)">
                            <i class="bi bi-trash"></i>
                        </a>
                    </td>
                </tr>
            }

        </table>
        <div class="pager">
            <p class="page-item">
                Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) / @Model.PageCount
            </p>

            <div class="pagination">
                @Html.PagedListPager(Model, page => Url.Action("Index", "AdminHome", new { page, status = status }),
           new PagedListRenderOptions
           {
               DisplayLinkToIndividualPages = true,
               DisplayPageCountAndCurrentLocation = false,
               LiElementClasses = new string[] { "page-item" }
           })
            </div>
        </div>
    </div>
</div>
@if (status == 3)
{
    <script>
        const st = document.getElementById('status')
        st.options[0].selected = true;
    </script>
}

@if (status == 1)
{
    <script>
        const st = document.getElementById('status')
        st.options[2].selected = true;
    </script>
}

@if (status == 0)
{
    <script>
        const st = document.getElementById('status')
        st.options[1].selected = true;
    </script>
}
<script>
    function change(obj) {
        const params = new Proxy(new URLSearchParams(window.location.search), {
            get: (searchParams, prop) => searchParams.get(prop),
        });
        let value = params.find;
        if (value !== null) {
            window.location.href = '/Admin/AdminHome/Index?find=' + value + '&page=1&status=' + obj.value;
        } else {
            window.location.href = '/Admin/AdminHome/Index?page=1&status=' + obj.value;
        }
    }
</script>

Management Debt/Areas/Admin/Views/AdminHome/addDebtor.cshtml
@model Management_Debt.Models.Debtor
@{
    ViewBag.Title = "Add Debtor";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
@{
    List<SelectListItem> listItems = new List<SelectListItem>();
    listItems.Add(new SelectListItem
    {
        Text = "Chưa trả hết nợ",
        Value = "0"
    });
    listItems.Add(new SelectListItem
    {
        Text = "Đã trả hết nợ",
        Value = "1",
        Selected = true
   });
    string message = ViewBag.message;
    string z = ViewBag.m;
}

@section css{
    <link rel="stylesheet" href="~/Areas/Admin/Content/css/form.add.css" />
}
@if (message != null && z != null)
{
    <p class="message @z">@message</p>
}
<section id="content1" class="container1">
    @using (Html.BeginForm("addDebtor", "AdminHome", FormMethod.Post))
    {
        <h1>Form add information of debtor</h1>
        <p>Please type new information.</p>
        <hr>
        <label for="id"><b>ID</b></label>
        @Html.TextBoxFor(m => m.did, new { @placeholder = "Type id of debtor", @required = "required", @autofocus = "autofocus" })

        <label for="name"><b>Full name</b></label>
        @Html.TextBoxFor(m => m.full_name, new { @placeholder = "Type full name of debtor", @required = "required" })

        <label for="email"><b>Email</b></label>
        @Html.TextBoxFor(m => m.email, new { @placeholder = "Type email of debtor", @type = "email", @required = "required" })

        <label for="birthday"><b>Birthday</b></label>
        @Html.TextBoxFor(m => m.birthday, new { @type = "date", @required = "required" })

        <label for="status"><b>Status</b></label>

        @Html.DropDownListFor(m => m.status, listItems, "-- Select Status --")


        <label for="lyric"><b>Address</b></label>
        @Html.TextAreaFor(m => m.address, new { @rows = "4", @placeholder = "Type address of debtor" })

        <div class="clearfix">
            <input type="submit" name="add" value="Add" class="btnAdd2" />
        </div>
    }
</section>

Management Debt/Areas/Admin/Views/AdminHome/updateDebtor.cshtml
@model Management_Debt.Models.Debtor
@{
    ViewBag.Title = "Edit Debtor";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
@{
    List<SelectListItem> listItems = new List<SelectListItem>();
    listItems.Add(new SelectListItem
    {
        Text = "Chưa trả hết nợ",
        Value = "0"
    });
    listItems.Add(new SelectListItem
    {
        Text = "Đã trả hết nợ",
        Value = "1",
        Selected = true
    });
    string message = ViewBag.message;
    string z = ViewBag.m;
}

@section css{
    <link rel="stylesheet" href="~/Areas/Admin/Content/css/form.add.css" />
}

@if (Model != null)
{
    string date = Convert.ToDateTime(Model.birthday).Date.ToString("yyyy-MM-dd");
    if (message != null && z != null)
    {
        <p class="message @z">@message</p>
    }
    <section id="content1" class="container1">
        @using (Html.BeginForm("updateDebtor", "AdminHome", new { id = Model.did }, FormMethod.Post))
        {
            <h1>Form add information of debtor</h1>
            <p>Please type new information.</p>
            <hr>
            <label for="id"><b>ID</b></label>
            @Html.TextBoxFor(m => m.did, new { @value = Model.did, @readonly = "@readonly" })

            <label for="name"><b>Full name</b></label>
            @Html.TextBoxFor(m => m.full_name, new { @value = Model.full_name, @required = "required" })

            <label for="email"><b>Email</b></label>
            @Html.TextBoxFor(m => m.email, new { @value = Model.email, @type = "email", @required = "required" })

            <label for="birthday"><b>Birthday</b></label>
            @Html.TextBoxFor(m => m.birthday, new { @value = date, @type = "date", @required = "required" })

            <label for="status"><b>Status</b></label>

            @Html.DropDownListFor(m => m.status, listItems, "-- Select Status --")


            <label for="lyric"><b>Address</b></label>
            @Html.TextAreaFor(m => m.address, new { @rows = "4", @value = Model.address, @required = "required" })

            <div class="clearfix">
                <input type="submit" name="add" value="Edit" class="btnAdd2" />
            </div>
        }
    </section>
}
else
{
    <div style="color: red; margin: 30px;">Vui lòng chọn người nợ trước</div>
}